site_name: Grupo 10 - Compiladores 1
repo_url: https://github.com/Davicamilo23/2025.2-Compiladores-1_Grupo-10

nav:
  - Home: index.md
  - Sobre o Projeto: sobre.md
  - Guia de Instalação e Uso: guia-instalacao-uso.md
  - Manual Técnico: MANUAL_TECNICO.md
  - Tokens e Estrutura: linguagem-fonte-c.md
  - Sprint 1:
    - Sumário: SUMARIO_EXECUTIVO.md
    - Detalhes Técnicos: DOCUMENTACAO_SPRINT1.md
    - Changelog: CHANGELOG.md
  - Testes:
    - Guia: README_TESTES.md
  - Atas:
    - Reunião 01: atas/ata01.md
    - Reunião 02: atas/ata02.md
    - Reunião 03: atas/ata03.md
    

theme:
  name: material
  palette:
    - scheme: default
      primary: cyan
      accent: blue-grey
      toggle:
        icon: material/brightness-2
        name: Mudar para modo escuro
    - scheme: slate
      primary: cyan
      accent: blue-grey
      toggle:
        icon: material/brightness-7
        name: Mudar para modo claro

  font:
    text: Poppins
  
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.top

extra:
  generator: false
